Repository sign-muscat/frontSign, pull requests merged in 2024-07, with the labels that each got.

#1 #1 front react 환경 셋팅
  package-lock.json
  package.json
  src/index.js
Labels: ⚙️Setting

#3 #2 프론트 폰트 및 레이아웃 수정
  package.json
  src/App.js
  src/components/Header.js
  src/components/button/SkipButton.js
  src/index.css
  src/index.js
  src/layouts/MainLayout.js
  src/pages/GamePage.js
  src/pages/MainPage.js
Labels: 🎨Layout, ⚙️Setting

#7 #2 프론트 폰트 및 레이아웃 수정 (#3)
  package.json
  src/App.js
  src/components/Header.js
  src/components/button/SkipButton.js
  src/index.css
  src/index.js
  src/layouts/MainLayout.js
  src/pages/GamePage.js
  src/pages/MainPage.js
Labels: ⚙️Setting

#9 #4 Design Finish Page
  package.json
  src/App.js
  src/components/button/RegistRank.js
  src/components/item/QuestionTableItem.js
  src/components/table/QuestionTable.js
  src/pages/ResultPage.js
Labels: ✨ Feature, 🎨Layout

#14 #4 게임 결과 저장 구현
  src/apis/RankAPICalls.js
  src/apis/api.js
  src/components/button/RegistRank.js
  src/modules/RankReducer.js
  src/modules/index.js
  src/pages/ResultPage.js
  src/utils/DifficultyUtil.js
  src/utils/ToastUtils.js
Labels: ✨ Feature

#15 #10 정답 모달 추가
  public/congrats.webp
  src/components/Modal.js
  src/components/SuccessModal.js
Labels: ✨ Feature, 🎨Layout

#16 #11 메인 페이지 디자인
  src/HandDetection.js
  src/components/button/LevelButton.js
  src/components/item/RankTableItem.js
  src/components/table/RankTable.js
  src/layouts/MainLayout.js
  src/pages/MainBody.js
  src/theme/theme.js
Labels: 🎨Layout

#18 #17 타이머 디자인
  src/HandDetection.js
  src/components/CountdownCircleTimer.js
Labels: ✨ Feature, 🎨Layout

#20 #19 게임 페이지 디자인 적용
  src/HandDetection.js
  src/pages/MainPage.js
Labels: ✨ Feature, 🎨Layout

#22 #21 페이지 컴포넌트화
  src/App.js
  src/HandDetection.js
  src/apis/GameAPICalls.js
  src/components/TodayRank.js
  src/components/WordStepper.js
  src/components/button/RegistRank.js
  src/modules/GameReducer.js
  src/modules/index.js
  src/pages/GamePage.js
  src/pages/MainBody.js
  src/utils/DifficultyUtil.js
Labels: ✨ Feature, 🔧Refactor

#25 #24 오답처리 기능 및 정답 판단 기능 추가
  src/HandDetection.js
Labels: ✨ Feature, 🔧Refactor

#28 #26 게임 문제 이미지
  babel.config.js
  jest.config.js
  package-lock.json
  package.json
  public/images/actionQuestion/easy/값.png
  public/images/actionQuestion/easy/너.png
  public/images/actionQuestion/easy/무지개_1.png
  public/images/actionQuestion/easy/무지개_2.png
  public/images/actionQuestion/easy/안경.png
  public/images/actionQuestion/easy/키_1.png
  public/images/actionQuestion/easy/키_2.png
  public/images/actionQuestion/hard/외할머니_1.png
  public/images/actionQuestion/hard/외할머니_2.png
  public/images/actionQuestion/hard/외할머니_3.png
  public/images/actionQuestion/hard/외할머니_4.png
  public/images/actionQuestion/hard/외할아버지_1.png
  public/images/actionQuestion/hard/외할아버지_2.png
  public/images/actionQuestion/hard/외할아버지_3.png
  public/images/actionQuestion/hard/외할아버지_4.png
  public/images/actionQuestion/normal/강아지_1.png
  public/images/actionQuestion/normal/강아지_2.png
  public/images/actionQuestion/normal/강아지_3.png
  public/images/actionQuestion/normal/강아지_4.png
  public/images/actionQuestion/normal/금연_1.png
  public/images/actionQuestion/normal/금연_2.png
  public/images/actionQuestion/normal/금연_3.png
  public/images/actionQuestion/normal/맛있다_1.png
  public/images/actionQuestion/normal/맛있다_2.png
  public/images/actionQuestion/normal/맛있다_3.png
  public/images/actionQuestion/normal/물음_1.png
  public/images/actionQuestion/normal/물음_2.png
  public/images/actionQuestion/normal/온도_1.png
  public/images/actionQuestion/normal/온도_2.png
  public/images/actionQuestion/normal/온도_3.png
  public/images/actionQuestion/normal/온도_4.png
  public/images/actionQuestion/normal/우리_1.png
  public/images/actionQuestion/normal/우리_2.png
  public/images/actionQuestion/normal/우리_3.png
  public/images/actionQuestion/normal/우리_4.png
  public/images/actionQuestion/normal/인정_1.png
  public/images/actionQuestion/normal/인정_2.png
  public/images/actionQuestion/normal/인정_3.png
  public/images/actionQuestion/normal/텔레비전_1.png
  public/images/actionQuestion/normal/텔레비전_2.png
  setupTests.js
  src/App.test.js
  src/HandDetection.js
  src/apis/GameAPICalls.js
  src/apis/api.js
  src/components/Header.js
  src/modules/GameReducer.js
  src/setupTests.js
  src/tests/components/CountdownCircleTimer.test.js
  src/tests/components/Hader.test.js
  src/tests/components/SuccessModal.test.js
  src/tests/layouts/MainLayout.test.js
Labels: ✨ Feature, 🔧Refactor

#30 #29 요청 리팩토링
  package-lock.json
  src/App.js
  src/HandDetection.js
  src/apis/GameAPICalls.js
  src/apis/RankAPICalls.js
  src/components/Header.js
  src/components/SuccessModal.js
  src/components/TodayRank.js
  src/components/button/RegistRank.js
  src/components/item/QuestionTableItem.js
  src/components/item/RankTableItem.js
  src/components/table/QuestionTable.js
  src/components/table/RankTable.js
  src/layouts/MainLayout.js
  src/modules/GameReducer.js
  src/modules/RankReducer.js
  src/pages/GamePage.js
  src/pages/ResultPage.js
  src/utils/DateUtils.js
Labels: 🔧Refactor

#31 #29 요청 리팩토링
  src/HandDetection.js
  src/apis/GameAPICalls.js
  src/components/SuccessModal.js
  src/components/table/RankTable.js
  src/modules/GameReducer.js
  src/pages/GamePage.js
Labels: 🔧Refactor
